name: Auto Label PRs and Issues

on:
  pull_request:
    types: [opened, closed] # It will run when a PR is opened or closed (after merging)
  issues:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Auto-label PRs and Issues
        if: ${{ github.event.pull_request.merged == true || github.event_name == 'issues' }} # Only label PR if it's merged
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            gssoc-ext,
            Hackathon Winner,
            hacktoberfest accepted,
            hacktoberfest
          github-token: ${{ secrets.GITHUB_TOKEN }}
